version: '3'
services:
  db:
    build:
      context: ./internal/postgresql
    environment:
      POSTGRES_DB: VK_Authorization
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  server:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres-data:
